version: '3.8'

services:
    database:
        container_name: postgres
        image: postgres:latest
        restart: unless-stopped
        environment:
            POSTGRES_DB: quarkus_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "8081:5432"
        networks:
            - quarkus-network
         
    quarkus-app:
        build:
            dockerfile: Dockerfile.native
        environment:
            DB_SOURCE: database
            DB_PORT: 5432
            DB_NAME: quarkus_db
            DB_USER: postgres
            DB_PASS: postgres
        ports:
            - "8080:8080"
        depends_on:
            - database
        networks:
            - quarkus-network

networks:
    quarkus-network:
        driver: bridge
        external: false